services:
  - type: web
    name: imas-backend
    env: node
    plan: free
    region: oregon
    branch: main
    autoDeploy: true

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
