name: 🚀 CD Deployment

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build . -t vivek17290/imas:backend
      
    - name: Login to Docker Hub
      run: echo "${{ secrets.VIVEK_DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.VIVEK_DOCKERHUB_USERNAME }}" --password-stdin
      
    - name: Push Docker image
      run: docker push vivek17290/imas:backend
    
    - name: Build Docker image pavithra
      run: docker build . -t pavithrakumarsahu/imas:backend
      
    - name: Login to Docker Hub pavithra
      run: echo "${{ secrets.PAVITHRA_DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.PAVITHRA_DOCKERHUB_USERNAME }}" --password-stdin
      
    - name: Push Docker image pavithra
      run: docker push pavithrakumarsahu/imas:backend