name: 🚀 CD Deployment

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . -t vivek17290/imas:backend -t pavithrakumarsahu/imas:backend

    - name: Login to Docker Hub (Vivek)
      run: echo "${{ secrets.VIVEK_DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.VIVEK_DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image (Vivek)
      run: docker push vivek17290/imas:backend

    - name: Login to Docker Hub (Pavithra)
      run: echo "${{ secrets.PAVITHRA_DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.PAVITHRA_DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image (Pavithra)
      run: docker push pavithrakumarsahu/imas:backend

    - name: Login to Docker Hub (Adi)
      run: echo "${{ secrets.ADI_DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.ADI_DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image (Adi)
      run: docker push aswathreddy/imas:backend

    - name: Login to Docker Hub (Rishi)
      run: echo "${{ secrets.RISHI_DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.RISHI_DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image (Rishi)
      run: docker push rishithreddy1942/imas:backend

    - name: Login to Docker Hub (Appu)
      run: echo "${{ secrets.APPU_DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.APPU_DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image (Appu)
      run: docker push appureddy/imas:backend
